### ISSUE TITLE
Conflict with framework method trigger

### ISSUE THREAD

**Issue by ghost** [br0sk/yii2-pusher#2]
Hi everybody, I want to report conflict error methods, one called "trigger" in yii2 and the other with the same name in the plugin, an display error that I show below:

![image](https://cloud.githubusercontent.com/assets/13141768/15200547/78431da2-17ad-11e6-9cce-a81e3f9a9c85.png)

It would be nice they renamed ;)

**Comment by luongtd** [comment]
I also encountered this error :+1:

**Comment by deshario** [comment]
Any Solution ?

**Comment by deshario** [comment]
You can use the original one in yii2. 
Note :  Don't need to require =>  __DIR__ . '/vendor/autoload.php';
![org](https://user-images.githubusercontent.com/11426727/32137564-9a2a9bee-bc4c-11e7-82d4-3e69405a216c.PNG)


# Model
    public function send_request($title,$message){
        $options = array(
            'cluster' => 'ap1',
            'encrypted' => true
        );
        $pusher = new Pusher(
            'auth-key',
            'secret',
            'app-id',
            $options
        );
        $data['title'] = $title;
        $data['message'] = $message;
        $pusher->trigger('main-channel', 'request-event', $data);
    }

# Controller
`  public function actionCreate(){
   $model->send_request('title','message');
  }`

**Comment by br0sk** [comment]
Please try version 1.0.0 it solves problem with name clash.
